### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by barksten** [RadiusNetworks/proximitykit-ios#4]
A crash caused by the framework requiring `NSLocationAlwaysUsageDescription` to be present in info.plist. It doesn't seem to accept `NSLocationWhenInUseUsageDescription`
This contrary to the documentation which states that:
> You will need to add one of the two keys:
> NSLocationAlwaysUsageDescription
> NSLocationWhenInUseUsageDescription

See [Getting started with Proximity Kit](http://proximitykit.radiusnetworks.com/docs/ios%2Fgetting-started) documentation

Tested with latest 1.0.4 (pre)release

**Comment by csexton** [comment]
@barksten Thanks for the catch, and letting us know. I've released an updated version that check for `NSLocationWhenInUseUsageDescription` *or* `NSLocationAlwaysUsageDescription`.

This is in the `1.0.5-pre` release available [here](https://github.com/RadiusNetworks/proximitykit-ios/releases/tag/v1.0.5).

Sorry about that, if you have any issues feel free to re-open this issue.

**Comment by barksten** [comment]
Issue still persist with 1.0.5

This is the stack trace:
*** Terminating app due to uncaught exception 'Missing info.plist key', reason: 'You must add NSLocationAlwaysUsageDescription key to your info.plist file.'
*** First throw call stack:
(
	0   CoreFoundation                      0x049e5946 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x0466ea97 objc_exception_throw + 44
	2   CoreFoundation                      0x049e5561 -[NSException raise] + 17
	3   McDonalds                           0x008d4c1d -[RPKManager checkForLocationAlwaysUsageDescription] + 381
	4   McDonalds                           0x008d2843 -[RPKManager initWithDelegate:andConfig:] + 195
	5   McDonalds                           0x008d252a +[RPKManager managerWithDelegate:] + 122

**Comment by csexton** [comment]
@barksten looks like I accidentally uploaded the 1.0.4 release in the zip file, I deleted that and [uploaded the proper version on the release](https://github.com/RadiusNetworks/proximitykit-ios/releases/tag/v1.0.5). You can verify by right clicking and "view info" on the framework bundle to view the version.

However, you may still need to use `NSLocationAlwaysUsageDescription`.  After talking to the team here and doing some initial testing, it seems that on iOS 8 that CoreLocation will monitoring for beacons or geofences to the app unless "always" is set for the location.

I will do more investigation to see what the options are.

**Comment by csexton** [comment]
@barksten we did some more research into the issue. I created a sample app and proved that with `NSLocationWhenInUseUsageDescription` set I can successfully range beacons. It can't, however, do any region monitoring.  This is something we could support, but it is a bit more involved than just updating the plist validation code.

I am guessing the vast majority of ProximityKit apps need both ranging and monitoring. I was curious, do you had a specific case for wanting foreground only with ProximityKit?

**Comment by mharper** [comment]
I definitely recall that over the summer (and possibly even production iOS 8.0) didn't range beacons at all without the "always" authorization.  But that was a long, long time ago in Internet/developer years.

**Comment by barksten** [comment]
I've verified the new build and it works for me. Thanks!
@mharper Makes sense (iOS 8 must have been the worst release yet..) I will have a look.

**Comment by barksten** [comment]
When using `NSLocationWhenInUseUsageDescription` or manually only allowing location when in use in device settings the Framework fails with the following error:
> Error Domain=ProximityKit Code=523 "Region Monitoring Not Authorized"
> UserInfo=0x17047a980 {NSLocalizedDescription=Region Monitoring Not Authorized}

**Comment by csexton** [comment]
@barksten that's what I was alluding to previously, we can't do region monitoring unless you request `NSLocationAlwaysUsageDescription`, and in the library we start region monitoring and ranging at the same time. So with the current version of ProximityKit you need to use the "always" permission.

So to work around this for now can you request that, and we would be happy to work through your use-case to make sure things are working how you need them to. If we need to we'll can add support for "InUse" but the library would have limited functionality.
